stages:
  - build

build:
  image: microsoft/dotnet
  stage: build
  artifacts: 
    paths:
    - Simkl.dll
  script:
    - cd Simkl-Emby
    - dotnet build -c GitLab
    - mv bin/GitLab/netstandard2.0/Simkl.dll ../